baseURL: http://down2trade.com/
languageCode: en-us
title: Down2Trade
disableKinds:
- taxonomy
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
params:
  openGraph: false
  description: Down2Trade is closed for business.
  font:
    name: "Open Sans"
    sizes: [400,600]
  section3: true
  footer:
    logo: down2trade-white-alt.svg
